USE [master]
GO

/****** Object:  Database [umbraco-cms]    Script Date: 04/15/2016 05:15:23 ******/
CREATE DATABASE [umbraco-cms] ON  PRIMARY 
( NAME = N'umbraco-cms', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\umbraco-cms.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'umbraco-cms_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\umbraco-cms_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [umbraco-cms] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [umbraco-cms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [umbraco-cms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [umbraco-cms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [umbraco-cms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [umbraco-cms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [umbraco-cms] SET ARITHABORT OFF 
GO

ALTER DATABASE [umbraco-cms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [umbraco-cms] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [umbraco-cms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [umbraco-cms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [umbraco-cms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [umbraco-cms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [umbraco-cms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [umbraco-cms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [umbraco-cms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [umbraco-cms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [umbraco-cms] SET  DISABLE_BROKER 
GO

ALTER DATABASE [umbraco-cms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [umbraco-cms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [umbraco-cms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [umbraco-cms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [umbraco-cms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [umbraco-cms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [umbraco-cms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [umbraco-cms] SET  READ_WRITE 
GO

ALTER DATABASE [umbraco-cms] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [umbraco-cms] SET  MULTI_USER 
GO

ALTER DATABASE [umbraco-cms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [umbraco-cms] SET DB_CHAINING OFF 
GO

